spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: hibernate.dialect.MySQL57InnoDBDialect
      open-in-view: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace